language: node_js
os: osx
osx_image: xcode7.3
node_js:
  - "7"
  - "6"
  - "4"
before_install:
  - nvm use --delete-prefix $TRAVIS_NODE_VERSION
  - uname -a
  - sw_vers
  - node --version
  - npm --version
